# Jekyll configuration for Veritheia documentation
title: Veritheia Documentation
description: An environment for inquiry - complete documentation
baseurl: "/veritheia" # the subpath of your site, e.g. /blog
url: "" # will be set automatically by GitHub Pages

# Theme settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Header pages (explicitly empty to disable auto-navigation)
header_pages: []

# Optional front matter for all pages
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/