name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Run tests (excluding integration tests)
      run: dotnet test --filter "Category!=Integration&Category!=LLMIntegration"
      env:
        TESTCONTAINERS_RYUK_DISABLED: true