name: Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    # GitHub Actions runners have Docker pre-installed
    # Testcontainers will use Docker to spin up PostgreSQL
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release
    
    - name: Test with Testcontainers
      run: |
        # Testcontainers needs Docker socket access
        dotnet test --configuration Release --verbosity normal \
          --logger "trx;LogFileName=test-results.trx" \
          --logger "console;verbosity=detailed"
      env:
        # Testcontainers configuration
        TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE: /var/run/docker.sock
        DOCKER_HOST: unix:///var/run/docker.sock
        # Improve Testcontainers performance
        TESTCONTAINERS_RYUK_DISABLED: true
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: '**/test-results.trx'
        retention-days: 30